
include ../common/common_mak
LibName = libSynanDmn$(ct)


objects = \
JVisualSynAnParamBuilder.o$(ct) \
SynanDmn.o$(ct) \
../common/string_socket.o$(ct) \
../common/SyntaxHolder.o$(ct) \
../common/BigramsReader.o$(ct) \
../common/MorhologyHolder.o$(ct)


include ../common/common_lib_mak

    