#profile = 1

include ../common/common_mak

LibName = libSynCommon$(ct)

objects =  \
Clause.o$(ct) \
ClauseCollection.o$(ct) \
CoverageKillHomonyms.o$(ct) \
BuildInitialClauses.o$(ct) \
FindTermins.o$(ct) \
FormatCaller.o$(ct) \
RelationsIterator.o$(ct) \
Group.o$(ct) \
oborot.o$(ct) \
Sentence.o$(ct) \
GLRFormats.o$(ct) \
SentencesCollection.o$(ct) \
stdafx.o$(ct) \
SynPlmLine.o$(ct) \
Word.o$(ct) SyntaxInit.o$(ct) \
MorphVariant.o$(ct) \
ThesaurusForSyntax.o$(ct)

include ../common/common_lib_mak


