link_pcre = 1

include ../common/common_mak

ExeName = TestLem$(ExeExten)

objects = TestLem.o$(ct) ../common/utilit.o$(ct)

libs = ../LemmatizerLib/libLemmatizer$(ct).$(lib_ext) \
../AgramtabLib/libAgramtab$(ct).$(lib_ext) \
../GraphanLib/libGraphan$(ct).$(lib_ext) \
../StructDictLib/libStructDict$(ct).$(lib_ext) \
../MorphWizardLib/libMorphWizard$(ct).$(lib_ext) 


include ../common/common_exe_mak



