include ../common/common_mak
LibName = libAgramtab$(ct)


objects = EngGramTab.o$(ct) \
GerGramTab.o$(ct) \
RusGramTab.o$(ct) \
agramtab_.o$(ct) \
../common/utilit.o$(ct)

include ../common/common_lib_mak
