include ../common/common_mak
ExeName = BigramsCGI$(ExeExten)
objects = Main.o$(ct) \
../common/cgic.o$(ct) \
../common/utilit.o$(ct)  \
../common/string_socket.o$(ct)


include ../common/common_exe_mak
