include ../common/common_mak
LibName = libTransfer$(ct)

objects = \
EngAdverbs.o$(ct) \
EngAlg_1.o$(ct) \
EngAlg_2.o$(ct) \
EngAlg_3.o$(ct) \
EngAlg_4.o$(ct) \
EngAlg_5.o$(ct) \
EngArticle.o$(ct) \
EngAtomic.o$(ct) \
EngBinaryTranslate.o$(ct) \
EngEquivs.o$(ct) \
EngHelper.o$(ct) \
EngInterp.o$(ct) \
EngNodeCreate.o$(ct) \
EngNoun.o$(ct) \
EngPrep.o$(ct) \
EngPrimitives.o$(ct) \
EngSynthes.o$(ct) \
EngTerminTranslate.o$(ct) \
EngTimeNodeTranslate.o$(ct) \
EngVerbTense.o$(ct) \
NodeHelper.o$(ct) \
StdAfx.o$(ct) \
TranseClause.o$(ct) \
TranslateToEnglish.o$(ct) \
TransPrepNoun.o$(ct) \
TransRels.o$(ct) \
TransRules.o$(ct) \
TransTense.o$(ct) 

include ../common/common_lib_mak

    