include ../common/common_mak
LibName = libSeman$(ct)


objects = \
AllRossesHolder.o$(ct) \
DictUnitInterp.o$(ct) \
GenerateNewForm.o$(ct) \
HierarchyHolder.o$(ct) \
RossHolder.o$(ct) \
RussianSynthesis.o$(ct) \
SemanHypotGraph.o$(ct) \
SemanPattern.o$(ct) \
SemanticAnswer.o$(ct) \
SemanticClause.o$(ct) \
SemanticColloc.o$(ct) \
SemanticCommon.o$(ct) \
SemanticCompar.o$(ct) \
SemanticGraph.o$(ct) \
SemanticIdealize.o$(ct) \
SemanticLength.o$(ct) \
SemanticLexFuncts.o$(ct) \
SemanticLexVariant.o$(ct) \
SemanticLoc.o$(ct) \
SemanticMNA.o$(ct) \
SemanticNumeral.o$(ct) \
SemanticRusPrimitives.o$(ct) \
SemanticsHolder.o$(ct) \
SemanticStrAn.o$(ct) \
SemanticSynRelation.o$(ct) \
SemanticThesaurus.o$(ct) \
SemanticTime.o$(ct) \
SemanticTree.o$(ct) \
SemanticWeight.o$(ct) \
SemPattern.o$(ct) \
SemStructureBuilder.o$(ct) \
stdafx.o$(ct) \
TransferSyntaxRelationToSemantics.o$(ct) \
TranslatorHolder.o$(ct) \
Valency.o$(ct) 


include ../common/common_lib_mak

    