include ../common/common_mak
ExeName = Bigrams$(ExeExten)
objects = Bigrams.o$(ct) 

libs = \
../GraphanLib/libGraphan$(ct).$(lib_ext) \
../StructDictLib/libStructDict$(ct).$(lib_ext)

include ../common/common_exe_mak
