include ../common/common_mak

LibName = libGerSynan$(ct)

objects =  \
GerAnalytical.o$(ct) \
GerBaseRules.o$(ct) \
GerBuildInitialClauses.o$(ct) \
GerClause.o$(ct) \
GerFormatCaller.o$(ct) \
GerGroup.o$(ct) \
GerOborot.o$(ct) \
GerSentence.o$(ct) \
GerSubject.o$(ct) \
GerSyntaxOpt.o$(ct) \
GerThesaurus.o$(ct) \
GerWord.o$(ct)

include ../common/common_lib_mak

