#profile = 1
link_pcre = 1
include ../common/common_mak
ExeName = TestSynan$(ExeExten)

objects = \
TestSynan.o$(ct) \
../common/utilit.o$(ct) \
../common/SyntaxHolder.o$(ct)  \
../common/MorhologyHolder.o$(ct)

libs = \
../GraphanLib/libGraphan$(ct).$(lib_ext) \
../TrigramLib/libTrigram$(ct).$(lib_ext) \
../RmlThesLib/libRmlThes$(ct).$(lib_ext) \
../LemmatizerLib/libLemmatizer$(ct).$(lib_ext) \
../AgramtabLib/libAgramtab$(ct).$(lib_ext) \
../MorphWizardLib/libMorphWizard$(ct).$(lib_ext) \
../MAPostLib/libMAPost$(ct).$(lib_ext) \
../StructDictLib/libStructDict$(ct).$(lib_ext) \
../SynCommonLib/libSynCommon$(ct).$(lib_ext) \
../GerSynanLib/libGerSynan$(ct).$(lib_ext) \
../EngSynanLib/libEngSynan$(ct).$(lib_ext) \
../GerPostMorph/libGerPostMorph$(ct).$(lib_ext) \
../SynanLib/libSynan$(ct).$(lib_ext) \
../SimpleGrammarLib/libSimpleGrammar$(ct).$(lib_ext)


include ../common/common_exe_mak

