//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Morphwizard.rc
//
#define IDR_MANIFEST                    1
#define ID_ANALYSE                      4
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_ASKSAVE                     102
#define IDS_OPENERR                     103
#define IDS_BADGSTR                     104
#define IDS_BADFSTR                     105
#define IDD_ACCENTWIZARDDLG             106
#define IDR_MAIN_FRAME                  128
#define IDR_MorphwizardTYPE             129
#define IDD_SLFEDIT                     129
#define IDD_MORHWIZARD_VIEW             130
#define IDR_MorphwizardTYPE2            130
#define IDR_SLF_TYPE                    130
#define ID_HELP_HELP                    131
#define IDD_PARAD_DIFF                  131
#define IDR_DIFF_TYPE                   131
#define IDD_INPUTBOX                    132
#define ID_TOOLS_SHOW_PARA_DIFF         132
#define IDD_TOOL_DELANC                 133
#define IDD_CHANGE_ALL_DLG              134
#define IDD_LOGIN                       135
#define ID_TOOLS_ACCENTWIZARD           135
#define IDD_PREDICT_PARAM               136
#define IDD_SLF_VIEW                    136
#define IDR_ACCELERATOR1                138
#define ID_TOOLS_SETPARADIGMNO          139
#define ID_TOOLS_SET_PARA_NO            139
#define IDI_READONLY                    180
#define IDC_STATUS                      1001
#define IDC_PARAD_1                     1001
#define IDC_SAVE_MRD                    1002
#define IDC_PREFIXES                    1002
#define IDC_GEN_BIN                     1003
#define IDC_EDIT1                       1003
#define IDC_PREFIXES_LBL                1003
#define IDC_LISTS_TITLE                 1004
#define IDC_PARAD_2                     1004
#define IDC_POS_TITLE                   1004
#define IDC_QUIT                        1005
#define IDC_COMMON_GRM_LBL              1005
#define IDC_FIND                        1006
#define IDC_CAPTION                     1006
#define IDC_TYPE_GRAMMEMS               1006
#define IDC_FIND_WHAT                   1007
#define IDC_GRAM_TITLE                  1007
#define IDC_PREDICTED_LIST              1008
#define IDC_PARA_TITLE                  1008
#define IDC_PRD_NO_TITLE                1008
#define IDC_REMOVE                      1009
#define IDC_CHANGE_ALL                  1009
#define IDC_PREDICT                     1010
#define IDC_LEMMA_LIST                  1010
#define IDC_ACC_MDL_NO_TITLE            1010
#define IDC_PREDICT_WHAT                1011
#define IDC_SAME_ACCENT_RADIO           1011
#define IDC_BASE_TITLE                  1011
#define IDC_FOUND_LIST                  1012
#define IDC_ANY_ACCENT_RADIO            1012
#define IDC_FREQ_DICT_EDIT              1012
#define IDC_PARADIGM_COMMENTS           1012
#define IDC_ADD                         1013
#define IDC_FREQ_DICT_STATIC            1013
#define IDC_PRD_LABEL_COMMENTS          1013
#define IDC_EDIT                        1014
#define IDC_FOUND_LIST2                 1015
#define IDC_MAX_COUNT_EDIT              1015
#define IDC_SLF                         1016
#define IDC_SPIN1                       1016
#define IDC_SET_PRD_COMMENTS            1016
#define IDC_LEDIT_SLF                   1017
#define IDC_FIX_ACCENT_BTN              1017
#define IDC_DICT_LIST                   1018
#define IDC_RADIO_NEW_ACC               1018
#define IDC_RADIO_OLD_ACC               1019
#define IDC_RADIO_OLD_NEW_ACC           1020
#define IDC_RADIO_PARTIAL_ACCENTED_PARA 1021
#define IDC_POSLIST                     1022
#define IDC_RADIO_ALL_NONACCENTED_PAPA  1022
#define IDC_GRAM_LIST                   1023
#define IDC_EDIT_PARTIAL_ACCENTED_PARA  1023
#define IDC_EDIT_ALL_NONACCENTED_PARA   1024
#define IDC_PRED_HINT                   1026
#define IDC_MAXIMAL                     1031
#define IDC_RFIND_LEM                   1034
#define IDC_RFIND_GRM                   1035
#define IDC_WORD_FORM                   1036
#define IDC_BROWSE                      1037
#define IDC_ANCODE                      1038
#define IDC_RADIO1                      1039
#define IDC_RADIO2                      1040
#define IDC_CTRL1                       1042
#define IDC_PRDNO                       1043
#define IDC_PRD_NO                      1043
#define IDC_FILTER                      1044
#define IDC_ACC_MDL_NO                  1044
#define IDC_BASE                        1045
#define IDC_MINFREQ                     1046
#define IDC_EDIT2                       1048
#define IDC_PARADIGM_TITLE              1048
#define IDC_RESULTS                     1048
#define IDC_FILE                        1049
#define IDC_FIND_BY_GRAMCODE            1050
#define IDC_FIND_BY_USERNAME            1051
#define IDC_CUSTOM1                     1052
#define IDC_RICHEDIT21                  1053
#define IDC_MINIMAL_FREQUENCE           1054
#define IDC_CHECK1                      1055
#define IDC_ONLY_MAIN_PART_OF_SPEECHES  1055
#define IDC_LIST_SHOW_CHECK             1055
#define IDC_ADD_PREFIX                  1057
#define IDC_CHANGE_PARADIGM             1059
#define IDC_READONLY_IMAGE              1077
#define ID_FIND_PARADIGM                32772
#define ID_SAVE_LIST_FILE               32774
#define ID_TOOLS_SAVE_LIST_FILE         32774
#define IDM_TOOL_DELANC                 32775
#define ID_TOOLS_DEL_ANCODE             32775
#define ID_IMPORT                       32776
#define ID_BUTTON32776                  32776
#define ID_TOOLS_IMPORT                 32776
#define ID_EXPORT                       32777
#define ID_TOOLS_EXPORT                 32777
#define ID_ADD_GRAMMEM                  32778
#define ID_SELECT_BY_FILE               32779
#define ID_TOOLS_SELECT_BY_FILE         32779
#define IDM_TOOL_DELDUP                 32780
#define ID_PREDICT_GENERATE             32781
#define ID_DELETE_BY_FILE               32782
#define ID_PACK_MRD                     32783
#define ID_TOOLS_PACK_MRD               32783
#define ID_FILE                         32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
