//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RossDev.rc
//
#define IDOK2                           2
#define IDD_ABOUTBOX                    100
#define IDR_ROSSDEV                     102
#define IDD_NEW_UNIT_WZD                102
#define IDB_SPLASH                      103
#define IDD_PROPPAGE_MEDIUM             106
#define IDD_ENGLISH_EQU                 107
#define IDD_WORDLIST_FORM               109
#define IDR_MAINFRAME                   128
#define IDR_ROSSDETYPE                  129
#define IDR_ARTICLETYPE                 130
#define IDR_POCKETTYPE                  131
#define IDD_INPUTBOX                    132
#define IDR_HIERARCHYTYPE               133
#define IDR_POPUP_WORDLIST              134
#define IDR_REPORTTYPE                  135
#define IDB_BITMAP1                     136
#define IDR_SEMANTICSTRUCTURE           137
#define IDD_ARTICLEFORM                 138
#define IDD_FIELDLIST_DIALOG            140
#define IDD_VALUEDLG                    141
#define IDD_SETEDITOR                   142
#define IDD_FORMULAEDITOR               143
#define IDD_POCKET_FORM                 145
#define IDD_SCHEME                      146
#define IDD_STATIS_DLG                  147
#define IDD_BASICDOMENDLG               148
#define IDD_IMPORT_DLG                  149
#define IDD_SCHEME_CHOICER              150
#define IDD_FIELDS_EDITOR_FORM          151
#define IDD_FIELDEDITOR_FORM            152
#define IDR_HIERARCHYMENU               156
#define IDD_DOMENLIST                   157
#define IDD_RICHEDITVIEW                158
#define IDD_POS_CHOICER                 159
#define IDD_WAIT_DLG                    164
#define IDD_DIALOG1                     165
#define IDR_MAINFRAM                    166
#define IDD_NEW_TEXTENTRY               169
#define IDD_REF_ARTICLES                170
#define IDD_HIERARCHYVIEW               173
#define IDB_BITMAP2                     176
#define IDI_READONLY                    180
#define IDD_FIND_BY_STR_DLG             190
#define IDD_FIND_WRONG_REFS             191
#define IDD_SIGNAT_EDITOR               192
#define IDD_PROGRESSBAR                 194
#define IDC_WORDLIST_GRID               1000
#define IDC_WORDLIST_ADD                1002
#define IDC_EDIT1                       1003
#define IDC_EDIT4                       1004
#define IDC_UNITS_SIZE                  1005
#define IDC_CAPTION                     1006
#define IDC_STATIC_RIGHT                1007
#define IDC_STATIC_LEFT                 1008
#define IDC_LEMMA_LOCATOR               1009
#define IDC_WORDLIST_DEL                1010
#define IDC_SET_SELECTED_BUTTON         1011
#define IDC_WORDLIST_ARTICLE_BTN        1012
#define IDC_ANIMATE_WAIT                1013
#define IDC_ARTICLEVIEW_MARKUP          1018
#define IDC_FLDSCROLL                   1019
#define IDC_ARTICLEVIEW_TEXTBTN         1020
#define IDC_LEDIT                       1021
#define IDC_ADD_BUTTON                  1027
#define IDC_FIELDLIST                   1029
#define IDC_ARTICLE_VIEW_DEL_FIELD      1031
#define IDC_ARTICLE_FORM_VALUE          1032
#define IDC_SETEDITOR_LIST              1035
#define IDC_SETEDITOR_ADD               1036
#define IDC_SETEDITOR_VALUE             1037
#define IDC_SETEDITOR_DEL               1038
#define IDC_MSFLEXGRID1                 1040
#define IDC_BUTTON1                     1041
#define IDC_BUTTON2                     1042
#define IDC_FORMULAEDITOR_VALUE         1043
#define IDC_VALUEDLG_SIGNATGROUP        1045
#define IDC_BUTTON3                     1046
#define IDC_BUTTON4                     1047
#define IDC_LIST1                       1048
#define IDC_RICHEDIT1                   1050
#define IDC_RADIO1                      1051
#define IDC_RADIO2                      1052
#define IDC_RADIO3                      1053
#define IDC_EDIT2                       1056
#define IDC_CHECK1                      1057
#define IDC_CHECK3                      1059
#define IDC_CHANGE_TITLE                1060
#define IDC_CHECK2                      1061
#define IDC_BACK_BTN                    1064
#define IDC_FORWARD_BTN                 1065
#define IDC_ORDERID_EDT                 1067
#define IDC_EDIT3                       1068
#define IDC_LEDIT1                      1069
#define IDC_EXPORT_CONSTANT             1070
#define IDC_SET_AUTHOR                  1072
#define IDC_ERR_PAD                     1074
#define IDC_READONLY_IMAGE              1077
#define IDC_COMBO1                      1078
#define IDC_FIND_IN_ALL_DICTS           1079
#define IDC_FIND_IN_ACTIVE_DICT         1080
#define IDC_FIELD_STR                   1081
#define IDC_AVAIL_DOMS                  1084
#define IDC_SIGNAT_DOMS                 1085
#define IDC_DELETE                      1086
#define IDC_ADD                         1087
#define IDC_LISTFIELD                   1088
#define IDC_HOTKEY1                     1089
#define IDC_PROGRESSBAR                 1090
#define IDC_Statis                      1091
#define IDC_RICHEDIT21                  1092
#define IDC_RICHEDIT22                  1093
#define IDC_GRID                        1094
#define IDC_DELETE_ALL_ITEMS            1096
#define IDC_SAVE_TO_FILES               1097
#define IDC_CHANGE_COLOR                1098
#define IDC_LOAD_CONST_FROM_FILES       1098
#define IDR_SAVE_ONLY_WORDLIST          32772
#define IDR_SELECT_ALL_WORDS            32773
#define IDR_DESELECT_ALL_WORDS          32774
#define IDR_SET_FILTER                  32776
#define IDR_SAVE_ROSS_TO_TXT            32778
#define IDD_EDIT_DISABLED_FIELDS        32779
#define ID_CHECK_ROSS                   32780
#define ID_RELOAD                       32780
#define ID_SEARCH_BY_ARTICLE            32781
#define IDR_SCHEME_ROSS                 32782
#define IDR_STATISTIC                   32783
#define ID_MENUITEM32784                32784
#define ID_MENUITEM32786                32786
#define ID_ADDNODE                      32787
#define ID_RELATION                     32788
#define ID_MENUITEM32788                32788
#define ID_DELRELATION                  32789
#define ID_VALENCIES                    32789
#define ID_MENUITEM32790                32790
#define ID_WORKRELATION                 32791
#define ID_SEMFET                       32791
#define ID_VALENCY_FILL                 32792
#define ID_STATISTIC_FIELD_VALUE        32793
#define ID_SORT_BY_LEMMA                32794
#define ID_SORT_BY_DATEANDTIME          32795
#define ID_SEMANTIC_STRUCTURE           32796
#define IDD_MINUS_LIST                  32797
#define IDD_APPENDARTICLE               32798
#define IDR_INVERT_SELECTION            32799
#define IDR_DEL_ALL_SELECTED            32800
#define ID_SELECT_AUTHOR                32801
#define ID_RUN_PROCEDURE_TO_BUILD_RUSSIAN_SEMANTIC_STRUCTURE 32802
#define IDR_GXI_STATISTICS              32803
#define ID_MENUITEM32804                32804
#define ID_MENUITEM32805                32805
#define ID_GET_SEMFILE                  32806
#define ID_BUTTON32808                  32808
#define ID_FIND_BY_STR                  32809
#define ID_OPEN_ALL_ROSSES              32810
#define ID_FIND_WRONG_REFS              32811
#define ID_SEMAN                        32812
#define ID_BUTTON32813                  32813
#define ID_MINIMIZE_ALL_DICTS           32814
#define IDD_EXPORT_ALL_DICTS            32815
#define EMPTY_ALL_DICTS                 32816
#define ID_IMPORT_ALL_DICTS             32817
#define ID_DEL_TEXT_DOMENS              32818
#define ID_ALL_DICT_ENTRIES             32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
