#profile = 1

include ../common/common_mak

LibName = libSynan$(ct)

objects =  \
Adverbs.o$(ct) \
AnalyticalForms.o$(ct) \
BaseRules.o$(ct) \
FragCoord.o$(ct) \
RusClause.o$(ct) \
RusThesaurus.o$(ct) \
foreign_term.o$(ct) \
FormatCallerInit.o$(ct)  \
FragDisrupt.o$(ct) \
RusParenthesis.o$(ct) \
FragPustycha.o$(ct) \
gen_chains.o$(ct) \
Gleiche.o$(ct) \
RusGroup.o$(ct)  \
HomonymsKiller.o$(ct) \
Names.o$(ct) \
noun_adjunct_group.o$(ct) \
NSO.o$(ct) \
Numbers.o$(ct) \
RusOborot.o$(ct) \
Participles.o$(ct) \
prepositions.o$(ct) \
RuleForSimilarNounGroupClauses.o$(ct) \
Selective.o$(ct) \
RusSentence.o$(ct) \
similar_adjs.o$(ct) \
similar_advs.o$(ct) \
similar_common.o$(ct)  \
similar_infs.o$(ct) \
similar_noun_groups.o$(ct)\
similar_numerals.o$(ct) \
StdSynan.o$(ct)  \
RusPlmLine.o$(ct) \
SynSubjPred.o$(ct) \
RusSyntaxOpt.o$(ct) \
RusFormatCaller.o$(ct) \
SynanDash.o$(ct) \
Verbs.o$(ct) \
RusWord.o$(ct) \
RusBuildInitialClauses.o$(ct)

include ../common/common_lib_mak



