link_pcre = 1
include ../common/common_mak

ExeName = SimpleGrammarPrecompiled$(ExeExten)
objects = SimpleGrammarPrecompiled.o$(ct)  

libs = \
../LemmatizerLib/libLemmatizer$(ct).$(lib_ext) \
../AgramtabLib/libAgramtab$(ct).$(lib_ext) \
../SimpleGrammarLib/libSimpleGrammar$(ct).$(lib_ext) \
../GraphanLib/libGraphan$(ct).$(lib_ext) \
../StructDictLib/libStructDict$(ct).$(lib_ext) \
../MorphWizardLib/libMorphWizard$(ct).$(lib_ext) 

include ../common/common_exe_mak

