#pragma once 

enum ESynRules {
	rule_for_numbers = 0,
	rule_for_num_complex,
	rule_for_noun_num,
	rule_for_names,
	rule_for_adv_adj,
	rule_for_similar_adjs,
	rule_for_modif_adj,
	rule_for_similar_advs,
	rule_for_similar_infs,
	rule_for_similar_comp_adjs,
	rule_for_comp_adv,
	rule_for_adv_verb,
	rule_for_noun_groups,
	rule_for_number_adverb,
	rule_for_number_noun,
	rule_for_rank_surname,
	rule_for_gen_chains,
	rule_for_from_compar,
	rule_for_preps,
	rule_for_prep_IZ,
	rule_for_selective_groups,
	rule_for_similar_noun_groups,
	rule_for_neg_verb,
	rule_for_dir_obj,
	rule_for_instr_obj,
	rule_for_dir_obj_rev,
	rule_for_verb_inf,
	rule_for_adv_adv,
	rule_for_web_addr,
	rule_for_similar_numerals,
	rule_for_noun_adjuncts,
	rule_adv_number_adverb,
	rule_for_approx_prep_noun,
	rule_for_partic_clause,
	rule_for_adj_in_commas_preposition,
	rule_for_plural_noun_adj,
	rule_for_noun_adj_postposition,
	rule_for_adjunct_group,
	rule_for_noun_detached_adj_postposition,
	rule_for_keyb,
	rule_for_disrupt_conj,
	rule_for_adv_predik,
	rule_for_whose_clause,
	rule_for_anat_compar,
	rule_for_similar_advs_comp_conj,
	rule_for_foreign_term,
	rule_for_preps_adj,
	rule_for_oborots

};

