
ExeName = TrigramRusCorporaXml$(ExeExten)
objects = main.o$(ct)  \
../common/utilit.o$(ct) \
./CookedSentence.o$(ct) \
../common/RusCorpXml.o$(ct) 

libs = ../tinyxml/libTinyXml$(ct).$(lib_ext) \
../TrigramLib/libTrigram$(ct).$(lib_ext)


include ../common/common_mak
include ../common/common_exe_mak
