
include ../common/common_mak

LibName = libBinaryDicts$(ct)

objects =  \
AspPairDict.o$(ct) \
BinaryDictionary.o$(ct) \
DerivDict.o$(ct) \
FreqDict.o$(ct) \
SetOfWordPairs.o$(ct) \
stdafx.o$(ct) \
SynDictionary.o$(ct)

include ../common/common_lib_mak



