
include ../common/common_mak
LibName = libSemanDmn$(ct)


objects = \
VisualGraph.o$(ct) \
translate.o$(ct) \
../common/SyntaxHolder.o$(ct) \
../common/MorhologyHolder.o$(ct) \
../common/string_socket.o$(ct)


include ../common/common_lib_mak

    