#ifndef rename_h_as7d46as4d
#define rename_h_as7d46as4d
#define pcre_callout internal_pcre_callout
#define pcre_compile internal_pcre_compile
#define pcre_compile2 internal_pcre_compile2
#define pcre_config internal_pcre_config
#define pcre_copy_named_substring internal_pcre_copy_named_substring
#define pcre_copy_substring internal_pcre_copy_substring
#define pcre_dfa_exec internal_pcre_dfa_exec
#define pcre_exec internal_pcre_exec
#define pcre_free internal_pcre_free
#define pcre_free_substring internal_pcre_free_substring
#define pcre_free_substring_list internal_pcre_free_substring_list
#define pcre_fullinfo internal_pcre_fullinfo
#define pcre_get_named_substring internal_pcre_get_named_substring
#define pcre_get_stringnumber internal_pcre_get_stringnumber
#define pcre_get_stringtable_entries internal_pcre_get_stringtable_entries
#define pcre_get_substring internal_pcre_get_substring
#define pcre_get_substring_list internal_pcre_get_substring_list
#define pcre_info internal_pcre_info
#define pcre_maketables internal_pcre_maketables
#define pcre_malloc internal_pcre_malloc
#define pcre_refcount internal_pcre_refcount
#define pcre_stack_free internal_pcre_stack_free
#define pcre_stack_malloc internal_pcre_stack_malloc
#define pcre_study internal_pcre_study
#define pcre_version internal_pcre_version
#define regcomp internal_regcomp
#define regerror internal_regerror
#define regexec internal_regexec
#define regfree internal_regfree
#endif
