include ../common/common_mak
LibName =  libTinyXml$(ct)
objects = tinystr.o$(ct) \
tinyxml.o$(ct) \
tinyxmlerror.o$(ct) \
tinyxmlparser.o$(ct) \
lex_util.o$(ct) \
action_store.o$(ct) \
node_set.o$(ct) \
tokenlist.o$(ct) \
xml_util.o$(ct) \
xpath_expression.o$(ct) \
xpath_processor.o$(ct) \
xpath_stack.o$(ct) \
xpath_static.o$(ct) \
xpath_stream.o$(ct) \
xpath_syntax.o$(ct)
include ../common/common_lib_mak
