
VPATH = ../

include ../common/common_mak


common_parms := -I. -DHAVE_CONFIG_H
include ../common/common_mak
LibName = libPCRE$(ct)


objects = pcre_chartables.o$(ct) \
pcre_compile.o$(ct) \
pcre_config.o$(ct) \
pcre_dfa_exec.o$(ct) \
pcre_exec.o$(ct) \
pcre_fullinfo.o$(ct) \
pcre_get.o$(ct) \
pcre_globals.o$(ct) \
pcre_info.o$(ct) \
pcre_maketables.o$(ct) \
pcre_newline.o$(ct) \
pcre_ord2utf8.o$(ct) \
pcre_refcount.o$(ct) \
pcre_study.o$(ct) \
pcre_tables.o$(ct) \
pcre_try_flipped.o$(ct) \
pcre_ucp_searchfuncs.o$(ct) \
pcre_valid_utf8.o$(ct) \
pcre_version.o$(ct) \
pcre_xclass.o$(ct) \
pcre_rml.o$(ct) \
pcreposix.o$(ct) 

include ../common/common_lib_mak
