include ../common/common_mak
LibName = libRmlThes$(ct)


objects = \
Concepts.o$(ct) \
Models.o$(ct) \
ThesOborots.o$(ct) \
Relats.o$(ct) \
StdRmlThes.o$(ct) \
Synonyms.o$(ct) \
Termins.o$(ct) \
Thesaurus.o$(ct)

include ../common/common_lib_mak

    