include ../common/common_mak
VPATH = ../
LibName = libGraphan$(ct)

objects =  \
C_desc.o$(ct) \
Consent.o$(ct) \
../common/gra_descr.o$(ct) \
Cs_hiera.o$(ct) \
GraphmatFile.o$(ct) \
HtmlConv.o$(ct) \
Nc_desc.o$(ct) \
Writegra.o$(ct) \
abbrev.o$(ct) \
graline.o$(ct) \
Oborots.o$(ct) \
UnitHolder.o$(ct) \
GraphanDicts.o$(ct) \
Sentences.o$(ct)

include ../common/common_lib_mak
